services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "your_password"]
    networks:
      - redis_network


  app:
    build: .
    container_name: myapp
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - redis_network
    ports:
      - "8080:8080"
    environment:
      - REDIS_PASSWORD=your_password
    command: /usr/local/bin/thumbnail
    restart: always

networks:
  redis_network:
    driver: bridge
