name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build Docker image
        run: |
          docker build -t myapp .

      - name: Run with Docker Compose
        run: |
          docker-compose up -d
          sleep 60

      - name: Run client commands inside the container
        run: |
          docker exec myapp /bin/sh -c "/usr/local/bin/client --async https://www.youtube.com/watch?v=tPiagp9t5is"
          docker exec myapp /bin/sh -c "/usr/local/bin/client --async https://www.youtube.com/watch?v=tPiagp9t5is,https://www.youtube.com/watch?v=dmx_8jo0eqE"
          docker exec myapp /bin/sh -c "/usr/local/bin/client https://www.youtube.com/watch?v=tPiagp9t5is,https://www.youtube.com/watch?v=dmx_8jo0eqE"

      - name: Tear down
        run: docker-compose down
